import turtle

turtle.pencolor("white")
turtle.color("blue")
turtle.speed(3)
turtle.shape("circle")
turtle.shapesize(0.5)
turtle.pensize(5)

turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)

turtle.penup()
turtle.goto(-25,25)
turtle.pendown()

turtle.color("black")
turtle.pencolor("black")
turtle.forward(150)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(150)
turtle.right(90)

turtle.done()
turtle.mainloop()